# Generated by Django 5.2 on 2025-04-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('matricula', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=11)),
                ('entrada', models.DateTimeField(default=None, null=True)),
                ('saida', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('entrada', models.DateTimeField(default=None, null=True)),
                ('saida', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
